### ISSUE TITLE
magyarlanc/ clojure  wrapper

### ISSUE THREAD

**Issue by damesek** [oroszgy/awesome-hungarian-nlp#28]
A mai nap elkeszitettem a magyarlanc Clojure wrapperet, elsosorban AI dolgokhoz. 
Hatha valakinek erdekes lehet a jovoben. https://github.com/damesek/eszterlanc

Udv,
Szabolcs

**Comment by oroszgy** [comment]
Thanks for the notification, just added it to the list.
